### ISSUE TITLE
Several bugs and a misleading User Guide description on batch export / import

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#862]
- [x] The given syntax to specify the code entry points with a batch export of an arrangement file (enh. #696) does not work as described under Linux (whereas Windows has no problems with it):
`structorizer.sh -x Oberon /home/bob/files/foo.arrz!test(7)!MAIN!sub(2-3)`.
- [x] If entry points are specified (on batch export of an arrangement) that would anyway be involved by another one then there is a risk that they are coded twice (cf. #836).
- [x] On batch parsing (import, enh. #179) the resulting arrangement file (if any) does not properly reflect the parameters of the referenced roots (particulary not minimum and maximum argument numbers). Therefore the arrangement file specification will usually not work for routines (because all entries feign main programs)

**Comment by codemanyak** [comment]
Well, the syntax just requires to enclose the arrangement specification with single quotes. This must be told in the User Guide.
